<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_3.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_4.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

    <xacro:property name="wheel_diameter" value="0.16" />
    <xacro:property name="wheel_width" value="0.084" />

<!--    <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" />-->

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <!-- Base link -->
    <link name="base_link">
        <inertial>
            <origin
                xyz="0.0 0.0 0.0"
                rpy="0 0 0" />
            <mass
                value="10" />
            <inertia ixx="0.1354" ixy="0" ixz="0"
             iyy="0.1354" iyz="0" izz="0.2667"/>
        </inertial>
        <visual>
            <origin
                    xyz="0 0 0.0"
                    rpy="1.57 0 -1.57" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base_link2.dae" />
            </geometry>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0"
                    rpy="0 0 0" />
          <geometry>
            <!-- <mesh
              filename="package://scout_description/meshes/scout_mini_base_link2.dae" /> -->
              <box size="0.4 0.4 0.05"/>
          </geometry>
        </collision>
    </link>

    <link name="box_link">
        <inertial>
            <origin
                xyz="0.0 0.0 0.0"
                rpy="0 0 0" />
            <mass
                value="5" />
            <inertia 
                ixx="0.054166666667" 
                ixy="0" 
                ixz="0"
                iyy="0.075" 
                iyz="0"
                izz="0.054166666667"/>
            </inertial>
        <visual>
            <origin
                    xyz="0.0 0.0 0.0"
                    rpy="0.0 0.0 3.14" />
            <geometry>
                <mesh filename="package://scout_description/meshes/box_link.STL" />
            </geometry>
            <material name = "red">
            <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0.1"
                    rpy="1.57 0 1.57" />
          <geometry>
            <box size="0.3 0.2 0.3"/>
          </geometry>
        </collision>
    </link> 

    <joint name="box_joint" type="fixed">
        <origin xyz="0 0 0.055" rpy="0 0 3.14" />
        <parent link="base_link" />
        <child link="box_link" />
    </joint>

 <link name="laser_link">
        <inertial>
            <origin
                xyz="0.0 0.0 0.0"
                rpy="0 0 0" />
            <mass
                value="0.1" />
            <inertia
                ixx="0.0088463"
                ixy="2.0356E-05"
                ixz="-0.00047464"
                iyy="0.0066478"
                iyz="-6.9288E-06"
                izz="0.01219" />
        </inertial>
        <visual>
            <origin
                    xyz="0.0 0.0 0.0"
                    rpy="0.0 0.0 0.0" />
            <geometry>
                    <cylinder radius="0.01" length="0.01"/>
            </geometry>
            <material name = "red">
            <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0.31"
                    rpy="0 0 0" />
          <geometry>
                    <cylinder radius="0.06" length="0.1"/>
          </geometry>
        </collision>
    </link>

    <joint name="laser_joint" type="fixed">
        <origin xyz="0 0 0.23" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="laser_link" />
    </joint>

 <link name="camera_link">
        <inertial>
            <origin
                xyz="0.0 0.0 0.0"
                rpy="0 0 0" />
            <mass
                value="0.1" />
            <inertia
                ixx="0.0088463"
                ixy="2.0356E-05"
                ixz="-0.00047464"
                iyy="0.0066478"
                iyz="-6.9288E-06"
                izz="0.01219" />
        </inertial>
        <visual>
            <origin
                    xyz="0.0 0.0 0.0"
                    rpy="0.0 0.0 0.0" />
            <geometry>
                    <box size="0.01 0.01 0.01"/>
            </geometry>
            <material name = "red">
            <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0.31"
                    rpy="0 0 0" />
          <geometry>
                    <box size="0.01 0.01 0.01"/>
          </geometry>
        </collision>
    </link>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0.2 0 0.16" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="camera_link" />
    </joint>

<!-- 
    <link name="inertial_link">
        <inertial>
            <mass value="60" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint> -->

    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->

    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_mini_wheel_1 wheel_prefix="front_left" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_1>
    <xacro:scout_mini_wheel_2 wheel_prefix="rear_left" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_2>
    <xacro:scout_mini_wheel_3 wheel_prefix="front_right" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_3>
    <xacro:scout_mini_wheel_4 wheel_prefix="rear_right" wheel_diameter="${wheel_diameter}" wheel_width="${wheel_width}">
    <!--<origin
           xyz="0 0 0"
           rpy="0 0 0" />-->
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_4>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find scout_description)/urdf/scout_mini.gazebo" />
</robot>
